package:
    type:           yii2-extension
    name:           hidev-pypi
    title:          PyPI plugin for HiDev
    headline:       HiDev PyPI
    keywords:       hidev, pypi, packagist, plugin
    namespace:      hidev\pypi
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.

        This plugin enables [PyPI](https://pypi.python.org/pypi) and [pip](https://pip.pypa.io/) support for HiDev.

require:
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-readme:        "*@dev"
    hiqdev/hidev-travis:        "*@dev"
    hiqdev/hidev-vendor:        "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-composer:      "*@dev"
    hiqdev/hidev-scrutinizer:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"
